# Generated by Django 5.1 on 2024-08-09 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cruso',
            new_name='Curso',
        ),
        migrations.RenameModel(
            old_name='Estudate',
            new_name='Estudante',
        ),
    ]
